name: Run Email Tracker

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Export GOOGLE_CREDS to environment
        run: echo "GOOGLE_CREDS=${{ secrets.GOOGLE_CREDS }}" >> $GITHUB_ENV

      - name: Run script
        run: python log.py
